# Generated by Django 4.0.4 on 2022-05-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0003_remove_object_tusks_tusk_object_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusk',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tusks', to='tusk_manager.object'),
        ),
    ]
