# Generated by Django 4.0.4 on 2022-05-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0004_alter_tusk_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tusk',
            new_name='Task',
        ),
    ]
