# Generated by Django 4.0.4 on 2022-05-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0006_task_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategories',
            new_name='Categories',
        ),
    ]
