# Generated by Django 4.0.4 on 2022-05-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0007_rename_servicecategories_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isWorker',
            field=models.BooleanField(default=True, verbose_name='Отображать в приложении'),
        ),
    ]
