# Generated by Django 4.0.4 on 2022-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0008_customuser_isworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='', max_length=255, verbose_name='E-mail'),
        ),
    ]
