# Generated by Django 4.0.4 on 2022-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusk_manager', '0013_alter_object_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='url',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
